/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 12.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

module relu(g_input, e_input, o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  input [31:0] g_input;
  input [31:0] e_input;
  output [31:0] o;
  ANDN _63_ (
    .A(_16_),
    .B(_24_),
    .Z(_48_)
  );
  ANDN _64_ (
    .A(_17_),
    .B(_24_),
    .Z(_49_)
  );
  ANDN _65_ (
    .A(_18_),
    .B(_24_),
    .Z(_50_)
  );
  ANDN _66_ (
    .A(_19_),
    .B(_24_),
    .Z(_51_)
  );
  ANDN _67_ (
    .A(_20_),
    .B(_24_),
    .Z(_52_)
  );
  ANDN _68_ (
    .A(_21_),
    .B(_24_),
    .Z(_53_)
  );
  ANDN _69_ (
    .A(_23_),
    .B(_24_),
    .Z(_55_)
  );
  ANDN _70_ (
    .A(_00_),
    .B(_24_),
    .Z(_32_)
  );
  ANDN _71_ (
    .A(_11_),
    .B(_24_),
    .Z(_43_)
  );
  ANDN _72_ (
    .A(_22_),
    .B(_24_),
    .Z(_54_)
  );
  ANDN _73_ (
    .A(_25_),
    .B(_24_),
    .Z(_56_)
  );
  ANDN _74_ (
    .A(_26_),
    .B(_24_),
    .Z(_57_)
  );
  ANDN _75_ (
    .A(_27_),
    .B(_24_),
    .Z(_58_)
  );
  ANDN _76_ (
    .A(_28_),
    .B(_24_),
    .Z(_59_)
  );
  ANDN _77_ (
    .A(_29_),
    .B(_24_),
    .Z(_60_)
  );
  ANDN _78_ (
    .A(_30_),
    .B(_24_),
    .Z(_61_)
  );
  ANDN _79_ (
    .A(_31_),
    .B(_24_),
    .Z(_62_)
  );
  ANDN _80_ (
    .A(_01_),
    .B(_24_),
    .Z(_33_)
  );
  ANDN _81_ (
    .A(_02_),
    .B(_24_),
    .Z(_34_)
  );
  ANDN _82_ (
    .A(_03_),
    .B(_24_),
    .Z(_35_)
  );
  ANDN _83_ (
    .A(_04_),
    .B(_24_),
    .Z(_36_)
  );
  ANDN _84_ (
    .A(_05_),
    .B(_24_),
    .Z(_37_)
  );
  ANDN _85_ (
    .A(_06_),
    .B(_24_),
    .Z(_38_)
  );
  ANDN _86_ (
    .A(_07_),
    .B(_24_),
    .Z(_39_)
  );
  ANDN _87_ (
    .A(_08_),
    .B(_24_),
    .Z(_40_)
  );
  ANDN _88_ (
    .A(_09_),
    .B(_24_),
    .Z(_41_)
  );
  ANDN _89_ (
    .A(_10_),
    .B(_24_),
    .Z(_42_)
  );
  ANDN _90_ (
    .A(_12_),
    .B(_24_),
    .Z(_44_)
  );
  ANDN _91_ (
    .A(_13_),
    .B(_24_),
    .Z(_45_)
  );
  ANDN _92_ (
    .A(_14_),
    .B(_24_),
    .Z(_46_)
  );
  ANDN _93_ (
    .A(_15_),
    .B(_24_),
    .Z(_47_)
  );
  assign o[31] = 1'b0;
  assign _16_ = g_input[24];
  assign _24_ = g_input[31];
  assign o[24] = _48_;
  assign _17_ = g_input[25];
  assign o[25] = _49_;
  assign _18_ = g_input[26];
  assign o[26] = _50_;
  assign _19_ = g_input[27];
  assign o[27] = _51_;
  assign _20_ = g_input[28];
  assign o[28] = _52_;
  assign _21_ = g_input[29];
  assign o[29] = _53_;
  assign _23_ = g_input[30];
  assign o[30] = _55_;
  assign _00_ = g_input[0];
  assign o[0] = _32_;
  assign _11_ = g_input[1];
  assign o[1] = _43_;
  assign _22_ = g_input[2];
  assign o[2] = _54_;
  assign _25_ = g_input[3];
  assign o[3] = _56_;
  assign _26_ = g_input[4];
  assign o[4] = _57_;
  assign _27_ = g_input[5];
  assign o[5] = _58_;
  assign _28_ = g_input[6];
  assign o[6] = _59_;
  assign _29_ = g_input[7];
  assign o[7] = _60_;
  assign _30_ = g_input[8];
  assign o[8] = _61_;
  assign _31_ = g_input[9];
  assign o[9] = _62_;
  assign _01_ = g_input[10];
  assign o[10] = _33_;
  assign _02_ = g_input[11];
  assign o[11] = _34_;
  assign _03_ = g_input[12];
  assign o[12] = _35_;
  assign _04_ = g_input[13];
  assign o[13] = _36_;
  assign _05_ = g_input[14];
  assign o[14] = _37_;
  assign _06_ = g_input[15];
  assign o[15] = _38_;
  assign _07_ = g_input[16];
  assign o[16] = _39_;
  assign _08_ = g_input[17];
  assign o[17] = _40_;
  assign _09_ = g_input[18];
  assign o[18] = _41_;
  assign _10_ = g_input[19];
  assign o[19] = _42_;
  assign _12_ = g_input[20];
  assign o[20] = _44_;
  assign _13_ = g_input[21];
  assign o[21] = _45_;
  assign _14_ = g_input[22];
  assign o[22] = _46_;
  assign _15_ = g_input[23];
  assign o[23] = _47_;
endmodule
